### ISSUE TITLE
monitor two websites

### ISSUE THREAD

**Issue by GMF-2016** [novakin/dns-failover-cloudflare-monit#1]
can another line be added to cloudflare.conf to monitor two sites? i.e. www.example.com and www.example2.com

thanks,
Greg

**Comment by novakin** [comment]
Hi Greg,

In your case, example.com and example2.com are hosted on the same server ?

**Comment by GMF-2016** [comment]
different servers, different IP addresses.

**Comment by novakin** [comment]
Then it's a bad idea to add extra sites in cloudflare.conf.

Download the files twice and configure them for each of your sites

**Comment by GMF-2016** [comment]
thanks for that. Sorry to be a pain but is it possible to failover to a DNS entry instead of an IP in the tomain.sh and tobackup.sh config files?
Our failover server(Microsoft Azure) appears to use dynamic IP address for it's DNS

**Comment by novakin** [comment]
Yes you can do that. It's not a big deal at all.

Make sure the record you want to update is a CNAME and not a A record on cloudflare website
then in tobackup.sh files configure the IP variable as a domain.

`ip=example2.com`

**Comment by GMF-2016** [comment]
cool, thanks.
so we need a cname for our backup site on running on Azure?

**Comment by novakin** [comment]
Yes you need to properly configure your DNS
