### ISSUE TITLE
https:// website issues

### ISSUE THREAD

**Issue by webhostingdoo** [novakin/dns-failover-cloudflare-monit#3]
Hi mate

I am a noob and my issue might not be related to https but let me elaborate please.

"tomain" and "tobackup" scripts are working just fine when manually executed.
However, when I shut down Nginx on the main server those scripts aren't executed.

When I run "monit status" I get the info the host ping time is 0
So I presume it's wrong

```
Remote Host 'www.domain.com'
  status                            Online with all services
  monitoring status                 Monitored
  ping response time                0.000s
  data collected                    Tue, 06 Dec 2016 13:10:00

```

Do you have some tips on how to troubleshoot this.
*There is a http to https redirection in the Nginx conf

Thanks!

**Comment by novakin** [comment]
Hi,

How long did you wait ?
Monit will need to receive 1 second timeouts for 4 cycles

**Comment by webhostingdoo** [comment]
I have waited a couple of minutes
Is this normal?
 ping response time                0.000s

**Comment by novakin** [comment]
Are you using the cloudflare always online feature ?
Please also change your monitoring check to ping the website IP and not the fqdn

**Comment by webhostingdoo** [comment]
Yes, that's correct!
omg, it has to be it
can't wait to try it out
Thanks bro!

**Comment by novakin** [comment]
That's why it doesnt work. You are checking the wrong IP, your domain redirects to cloudflare server.

Change the monitoring host, ping the server IP address instead

**Comment by webhostingdoo** [comment]
You mean like 
change this:
`check host www.domain.com with address 111.222.333.444
`
to this :
`check host 111.222.333.444 with address 111.222.333.444
`

**Comment by novakin** [comment]
Yes.
